name: Descargar Oracle Free Docker

on:
  push:
    branches:
      - main  # o la rama que uses

jobs:
  oracle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
      
      - name: Descargar la imagen de Oracle Free
        run: |
          docker pull gvenzl/oracle-free:latest

      - name: Guardar la imagen en un archivo
        run: |
          docker save gvenzl/oracle-free:latest -o oracle-free-latest.tar

      - name: Subir el archivo como artefacto (opcional)
        uses: actions/upload-artifact@v3
        with:
          name: oracle-free-image
          path: oracle-free-latest.tar
