name: Descargar Imagen Docker

on:
  push:
    branches:
      - main  # El flujo se ejecuta cada vez que hagas push en la rama main

jobs:
  descarga:
    runs-on: ubuntu-latest  # Usa un runner con Ubuntu

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3  # Solo para asegurarse de tener el repositorio en el runner

      - name: Descargar la imagen Docker
        run: |
          docker pull nginx:latest   # Aquí cambia 'nginx:latest' por la imagen que quieras

      - name: Guardar imagen como archivo
        run: |
          docker save nginx:latest -o nginx_latest.tar

      - name: Subir artefacto (opcional)
        uses: actions/upload-artifact@v3
        with:
          name: imagen-docker
          path: nginx_latest.tar
